🎛️  Implement Data converter for store model
milideal/MiliDeal pull request #16
Opened 2023-09-26 07:24 UTC by callendev20

Store 모델에 맞도록 아래와 같이 Data를 변환하는 코드입니다.
address는 도로명 주소로 통일했습니다.

- 원본 data
  ```JSON
    {
        "address_name": "서울 마포구 동교동 167-2",
        "category_group_code": "CT1",
        "category_group_name": "문화시설",
        "category_name": "문화,예술 > 영화,영상 > 영화관 > CGV",
        "distance": "",
        "id": "1066689336",
        "phone": "1544-1122",
        "place_name": "CGV 연남",
        "place_url": "http://place.map.kakao.com/1066689336",
        "road_address_name": "서울 마포구 양화로 186",
        "x": "126.92586924777187",
        "y": "37.55767576550851"
    }
    ```
- 변환된 data
  ```JSON
  {
      "address": "서울 마포구 양화로 186",
      "coordx": "126.92586924777187",
      "coordy": "37.55767576550851",
      "name": "CGV 연남"
  }
   ```

2023-09-26 08:48 UTC, woohyun212 requested changes
코드에 코멘트 남겼습니다.
영화관 타입이 아니라 문화 시설 타입으로 바꾸면하면 좋을 것 같네요

2023-09-26 08:48 UTC, woohyun212 commented on store/models.py
> +        ('theater', '영화관'),
영화관이 아니라 "문화여가시설" 로 묶어서 
"Culture leisure" 이니까... `culturel` 로 하는 게 좋을 것 같아요

2023-09-26 09:05 UTC, callendev20 commented on store/models.py
> +        ('theater', '영화관'),
완료했습니다~

2023-09-26 13:10 UTC, junglesub commented
키워드 관련해서 우려되는 상황이 있습니다.

먼저, 영어으로 표현할 수 있는 부분을 프랑스어로 표현하면서 가독성을 어렵게 만들지 않을까 염려됩니다.
`culturel` -> `culture` 으로 수정을 건의합니다.

또한, 가독성을 위해 약어가 아닌 풀 스펠링으로 적는 것은 어떨까 건의합니다.
`restau` -> `restaurant`

만약에 더 짧은 단어를 선호하신다면
`accommodation` -> `travel`
`restaurant` -> `food`
이런식으로 생각해보는 것도 방법인 것 같습니다.

2023-09-26 13:24 UTC, junglesub commented
잘 알려진 줄임말이 아닐경우 더욱 더 조심해야한다고 생각합니다.
"culture" 을 검색했을 때 "culture leisure" 을 파악하기에는 다소 무리가 있다고 생각합니다.

또한 영문으로 culture 만 적어도 우리가 흔히 생각하는 문화시설들을 의미하는데 충분하지 않을까 싶습니다.

아니면 - 진짜 "수상 스키" 같은 레저스포츠도 같이 포함하실 생각이신건가요?

2023-09-27 11:43 UTC, woohyun212 commented
그냥 "문화여가" 를 번역하면 "culture leisure" 가 되서 처음에 그런식으로 제안을 드린건데

> 먼저, 영어으로 표현할 수 있는 부분을 프랑스어로 표현하면서 가독성을 어렵게 만들지 않을까 염려됩니다. `culturel` -> `culture` 으로 수정을 건의합니다.
> 
> 또한, 가독성을 위해 약어가 아닌 풀 스펠링으로 적는 것은 어떨까 건의합니다. `restau` -> `restaurant`
> 
> 만약에 더 짧은 단어를 선호하신다면 `accommodation` -> `travel` `restaurant` -> `food` 이런식으로 생각해보는 것도 방법인 것 같습니다.
> 
> Naming convention 같은 경우 한번 정하면 변경하거나 되돌리기 어렵기 때문에 보수적으로 진행하면 어떨까 싶습니다

 @junglesub  님의 의견에 동의하는게 약어가 가독성이 떨어지는 것도 맞고
글자 수를 줄이는 건 단일 document의 용량을 최소화 하기 위함 일 것 같은데 그럴 것 같으면
그냥 string 말고 Integer한 값을 넣어서 표현하는게 나을 것 같구요

 `accommodation` -> `travel`, `restaurant` -> `food` 은 좋은 것 같습니다.
숙박 관련 할인 뿐만 아니라 기차 여행 할인 같은 것도 담을 수 있으면 좋겠네요.
근데 그러면 뭐 놀이공원 할인은 travel 일지 etc 인지 그런 구분도 애매해지긴 하네요

.

2023-09-27 11:46 UTC, merged